export const BACKEND_API_PATHS = {
   AUTH : "auth",
   SIGNIN : "signin",
   CREATEUSER : "createuser",
   SIGNOUT : "signout",
   USERS : "users",
   LEADS : "leads",
   VERIFYTOKEN :'verifytoken',
   TEAMLEAD : 'teamleads',
   LEADSTEAM : 'teamlead',
   EXECUTIVESINTEAM :  'executivesinteam',
   ADMINS : 'admins',
   SUPERADMINS : 'superadmin',
   LEADSASSIGN :'leadsassign',
   UPLOADSHEET : 'uploadsheet',
   REPORTS : 'reports',
   EXECUTIVE : 'executive',
   TEAM : 'team',
   OVERALL : 'overall',
   MANAGERASSIGN : 'managerassign',
};